batch_size: 1000
data_path: ../data/toy_dataset.parquet
dropout: 0.2
early_stop: null
encoding_dim: 8
features:
- track
- groundspeed
- altitude
- timedelta
fix_prior: true
gradient_clip_val: 0
h_dims:
- 64
- 64
- 64
info_features:
- latitude
- longitude
info_index: -1
kld_coef: 2
llv_coef: 1.0
lr: 0.001
lr_gamma: 1.0
lr_step_size: 200
lrgamma: 0.5
n_components: 1
network_name: fcvae
reg_pseudo: false
scale: 1.0
test_batch_size: null
train_ratio: 0.8
val_ratio: 0.2
